kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: lpr_service
  labels:
    app: lpr_service
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - lpr_service
        from:
          kind: ImageStreamTag
          name: 'lpr_service:latest'
    - type: ConfigChange
  replicas: 0
  revisionHistoryLimit: 5
  test: false
  selector:
    app: lpr_service
    deploymentconfig: lpr_service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lpr_service
        deploymentconfig: lpr_service
    spec:
      containers:
        - name: lpr_service
          image: lpr_service:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
