kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: kafka-consumer
  labels:
    app: kafka-consumer
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'kafka-consumer:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/ubi8/python-38:latest'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/red-hat-data-services/jumpstart-library'
    contextDir: patterns/kafka-consumer/src/kafka_consumer_app
  triggers:
    - type: ConfigChange
  runPolicy: Serial
