kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: kafka-consumer
  labels:
    app: kafka-consumer
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - kafka-consumer
        from:
          kind: ImageStreamTag
          name: 'kafka-consumer:latest'
  replicas: 1
  revisionHistoryLimit: 5
  test: false
  selector:
    app: kafka-consumer
    deploymentconfig: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
        deploymentconfig: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: kafka-consumer:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KAFKA_ENDPOINT
              value: core-kafka-kafka-bootstrap:9092
            - name: KAFKA_TOPIC
              value: topic-1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
