kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: generator
  labels:
    app: generator
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'generator:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'python-38:latest'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/red-hat-data-services/jumpstart-library'
    contextDir: pattern2-smart-city/source/SC_Generator
  triggers:
    - type: ConfigChange
  runPolicy: Serial
