apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secor
  name: secor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secor
  strategy: {}
  template:
    metadata:
      labels:
        app: secor
    spec:
      containers:
      - image: karansingh/secor-0.29-hadoop-2.9.2:latest
        name: secor-0-29-hadoop-2-9-2
        env:
        - name: ZOOKEEPER_PATH
          value: "/"
        - name: ZOOKEEPER_QUORUM
          value: "zoo-entrance:2181"
        - name: KAFKA_SEED_BROKER_HOST
          value: "kafka-core-site-kafka-brokers"
        - name: KAFKA_SEED_BROKER_PORT
          value: "9092"
        - name: AWS_ACCESS_KEY
          value: "7NS6UR50MP07EH5PQZ51"
        - name: AWS_SECRET_KEY
          value: "I0v9WC0XchfxHx3tPwj0a8JiMk2zUoq99LZHMj7M"
        - name: AWS_ENDPOINT
          value: "http://s3.data.local"
        - name: AWS_PATH_STYLE_ACCESS
          value: "true"
        - name: SECOR_S3_BUCKET
          value: "secor-bucket-9af181ee-216d-483e-8fb1-cdecc2015b63"
        - name: SECOR_GROUP
          value: "raw_logs"
        - name: SECOR_S3_PATH
          value: "kafka-messages"
        - name: KAFKA_OFFSETS_STORAGE
          value: "zookeeper"
        - name: SECOR_MAX_FILE_SECONDS
          value: "10"
        - name: SECOR_MAX_FILE_BYTES
          value: "10000"
        - name: SECOR_UPLOAD_MANAGER
          value: "com.pinterest.secor.uploader.S3UploadManager"
        - name: SECOR_MESSAGE_PARSER
          value: "com.pinterest.secor.parser.OffsetMessageParser"
        - name: DEBUG
          value: "True"
        - name: SECOR_KAFKA_TOPIC_FILTER
          value: "lpr"
        volumeMounts:
          - name: "local-mount"
            mountPath: "/mnt/secor_data/message_logs/partition"
      volumes:
      - name: local-mount
        emptyDir: {}
