kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: python-38
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/python-38
      generation: 1
      importPolicy: {}
      referencePolicy:
        type: Source
