apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql-db
  name: postgresql
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: postgresql
  type: ClusterIP
