apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: greeter
  namespace: smartcity
spec:
  template:
    spec:
      containers:
      - image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus
