apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: "knative-consumer-group"
  bootstrapServers:
    - core-kafka-kafka-bootstrap.smartcity.svc:9092
  topics:
    - lpr
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: greeter
