kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: events-service
  labels:
    app: events-service
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - events-service
        from:
          kind: ImageStreamTag
          name: 'events-service:latest'
  replicas: 1
  revisionHistoryLimit: 5
  test: false
  selector:
    app: events-service
    deploymentconfig: events-service
  template:
    metadata:
      labels:
        app: events-service
        deploymentconfig: events-service
    spec:
      containers:
        - name: events-service
          image: events-service:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DB_HOST
              value: postgresql
            - name: DB_NAME
              value: pgdb
            - name: DB_PASSWORD
              value: HT@1202k
            - name: DB_USER
              value: dbadmin
            - name: KAFKA_CONSUMER_GROUP_ID
              value: event_consumer_group
            - name: KAFKA_ENDPOINT
              value: >-
                kafka-core-site-kafka-bootstrap.lpr-core-site.svc.cluster.local:9092
            - name: KAFKA_TOPIC
              value: lpr
            - name: TABLE_NAME
              value: event
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
